---
name: Create Github Issue
description: Creates a new GitHub issue, or reuses an existing one by title (and optional labels)
author: Daniel Barnes
branding:
  icon: alert-octagon
  color: gray-dark

runs:
  using: node20
  main: ./dist/index.js

inputs:
  token:
    description: Your GitHub token (defaults to actions token)
    required: false
  owner:
    description: Repo owner; if not set, implied by context
    required: false
  repo:
    description: Repo name; if not set, implied by context
    required: false
  title:
    description: Issue title
    required: true
  body:
    description: Body content of the issue
    required: false
  milestone:
    description: Milestone associated with the issue
    required: false
  labels:
    description: CSV of labels (e.g. 'p0-critical,bug,aws'); used for creation and for reuse matching
    required: false
  assignees:
    description: CSV of GitHub usernames to assign (e.g. 'dacbd,nlf')
    required: false

  # ── New reuse options ─────────────────────────────────────────────────────────
  match_labels:
    description: "If true, match the issue by labels in addition to the title"
    required: false
    default: "true"
  close_comment:
    description: "Comment to post before closing duplicates"
    required: false
    default: "Closing as duplicate of canonical issue."

outputs:
  json:
    description: The JSON for the created or reused issue returned from the GitHub API
  html_url:
    description: The web URL of the created or reused issue
  number:
    description: "The created or reused issue number"
